### ISSUE TITLE
 [bug] Error when running any command on nodejs project using pnpm (pnpm dedupe) 

### ISSUE THREAD

**Issue by carere** [moonrepo/moon#1134]
As the title say

**Steps to reproduce**

I guess, create a pnpm monorepo and then use moon toolchain & repo

**Expected behavior**

Should works

**Screenshots**

```
▪▪▪▪ pnpm dedupe
/home/carere/.npm/_npx/08ff248d84e117fb/node_modules/@pnpm/lockfile-walker/node_modules/@pnpm/dependency-path/lib/index.js:76
    if (reference.startsWith('link:')) {
                  ^

TypeError: reference.startsWith is not a function
    at Object.refToRelative (/home/carere/.npm/_npx/08ff248d84e117fb/node_modules/@pnpm/lockfile-walker/node_modules/@pnpm/dependency-path/lib/index.js:76:19)
    at /home/carere/.npm/_npx/08ff248d84e117fb/node_modules/@pnpm/lockfile-walker/lib/index.js:62:32
    at Array.forEach (<anonymous>)
    at /home/carere/.npm/_npx/08ff248d84e117fb/node_modules/@pnpm/lockfile-walker/lib/index.js:61:14
    at Array.forEach (<anonymous>)
    at lockfileWalker (/home/carere/.npm/_npx/08ff248d84e117fb/node_modules/@pnpm/lockfile-walker/lib/index.js:54:17)
    at file:///home/carere/.npm/_npx/08ff248d84e117fb/node_modules/pnpm-deduplicate/dist/cli.mjs:59:9
    at Array.map (<anonymous>)
    at getAllDependencies (file:///home/carere/.npm/_npx/08ff248d84e117fb/node_modules/pnpm-deduplicate/dist/cli.mjs:56:40)
    at async findDuplicatePackages (file:///home/carere/.npm/_npx/08ff248d84e117fb/node_modules/pnpm-deduplicate/dist/cli.mjs:90:20)

Node.js v18.18.2
[ERROR 2023-10-21 23:41:12] log:run  Encountered a critical error, aborting the action pipeline  log.target="moon_action_pipeline::pipeline" log.module_path="moon_action_pipeline::pipeline" log.file="crates/core/action-pipeline/src/pipeline.rs" log.line=343
Error: process::failed

  × Process ~/.proto/tools/node/18.18.2/bin/npx failed with a 1 exit code.
```

**Environment**

```
  System:
    OS: Linux 6.2 elementary OS 7.1 Horus 7.1 Horus
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 8.34 GB / 15.50 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 18.18.1 - ~/.local/share/pnpm/node
    npm: 9.8.1 - ~/.local/share/pnpm/npm
    pnpm: 8.9.0 - ~/.local/share/pnpm/pnpm
  Managers:
    Apt: 2.4.10 - /usr/bin/apt
    Cargo: 1.73.0 - ~/.cargo/bin/cargo
  Utilities:
    CMake: 3.22.1 - /usr/bin/cmake
    Make: 4.3 - /usr/bin/make
    GCC: 11.4.0 - /usr/bin/gcc
    Git: 2.34.1 - /usr/bin/git
    Curl: 7.81.0 - /usr/bin/curl
  IDEs:
    Nano: 6.2 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
  Languages:
    Bash: 5.1.16 - /usr/bin/bash
    Perl: 5.34.0 - /usr/bin/perl
    Python3: 3.10.12 - /usr/bin/python3
    Rust: 1.73.0 - /home/carere/.cargo/bin/rustc
  Databases:
    SQLite: 3.37.2 - /usr/bin/sqlite3
  Browsers:
    Chrome: 118.0.5993.88
```

**Comment by carere** [comment]
I fixed it by adding `dedupeOnLockFileChange` to `false` under `node` entry in `toolchain.yml`
