### ISSUE TITLE
[bug] thread 'tokio-runtime-worker' panicked at 'Unable to get workspace root. Is moon running?

### ISSUE THREAD

**Issue by yonas** [moonrepo/moon#655]
```
$ moon init asdf
? Initialize moon into /memfs/misc/asdf? (y/n) ›thread 'tokio-runtime-worker' panicked at 'Unable to get workspace root. Is moon running?', crates/core/utils/src/lib.rs:49:17
                                                                                                                                                                              note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                      fish: Job 1, 'moon init asdf' terminated by signal SIGABRT (Abort)
```

OS: FreeBSD 13.1-RELEASE
moon v0.25.0

**Comment by milesj** [comment]
@yonas Is this the latest version (0.25)? I'm unable to reproduce.

```
$ moon init asd
✔ Initialize moon into ~/Projects/proto/asd? · yes
? Initialize Node.js? (y/n) ›
```

Is memfs a memory only file system? I'm not entirely sure moon would work there.

**Comment by yonas** [comment]
> @yonas Is this the latest version (0.25)? I'm unable to reproduce.

Yes, 0.25.0. commit 68ec8d9

> Is memfs a memory only file system? I'm not entirely sure moon would work there.

Yes. I tried on a regular disk, but the issue persists.

**Comment by yonas** [comment]
@milesj It works fine on Linux. This seems to be specific to FreeBSD.

**Comment by milesj** [comment]
Interesting. If you pass `RUST_BACKTRACE=1`, is there a stack trace? If so, send it over so I can pinpoint exactly where it's failing.

**Comment by milesj** [comment]
Ok that helps to narrow it down.

**Comment by yonas** [comment]
@milesj Thanks, we got a little further:

```
$ RUST_BACKTRACE=1 moon init asdf
✔ Initialize moon into /memfs/asdf? · yes
✔ Initialize Node.js? · yes

 NODE 

✔ Package manager? · npm
✔ Use package.json names as moon project aliases? · yes
✔ Infer package.json scripts as moon tasks? (not recommended) · yes
✔ Initialize TypeScript? · yes

 TYPESCRIPT 

✔ Use project references? · yes
✔ Route declaration output to moons cache? · yes
✔ Sync project references as path aliases? · yes

moon has successfully been initialized in /memfs/asdf
thread 'main' panicked at 'Unable to get workspace root. Is moon running?', crates/core/utils/src/lib.rs:49:17
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: moon_utils::get_workspace_root
   3: moon_launchpad::check_version::{{closure}}
   4: moon_cli::run_cli::{{closure}}
   5: moon::main::{{closure}}
   6: moon::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fish: Job 1, 'RUST_BACKTRACE=1 moon init asdf' terminated by signal SIGABRT (Abort)
```

**Comment by milesj** [comment]
That's odd. Init should create the `.moon` folder, so why does it still panic? 🤔

**Comment by milesj** [comment]
Oh, I get it now. The `.moon` folder is in the `asdf` folder, but you're actually up in the parent running the command. That makes more sense. Let me just work around this panic instead.

**Comment by yonas** [comment]
@milesj Thanks! Which commit fixes https://github.com/moonrepo/moon/issues/655#issuecomment-1450059596 ?
